// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ounlkhnkvfbvebjpolac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91bmxraG5rdmZidmVianBvbGFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NzU5MDgsImV4cCI6MjA1MjU1MTkwOH0.D62hGp9sLdw7aOhA2Wdin7p1ryvcAjr28YDhFlxhs9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);